automationcloud/autopilot

- packages/autopilot/src/main/settings.ts
- packages/autopilot/src/main/updater.ts
This PR allows manually adding `channel: 'beta'` to `settings.json` which, if everything is correct, will allow us to auto-update to prereleases (for internal QA purposes)
> feat: allow to auto-update to prereleases

- packages/autopilot/src/app/views/account-menu.vue
- packages/autopilot/src/app/views/first-run.vue
- fix:  avatar icon circle
- fix: bump new chromium version for `first-run.vue` (It struck me that how to inform the existing users to download new chromium version)
> fix: make avatar icon circle, bump chromium version

- packages/autopilot/src/app/components/signin-warning.vue
- packages/autopilot/src/app/controllers/api-login.ts
- packages/autopilot/src/app/entrypoint.ts
- packages/autopilot/src/app/provider.ts
- packages/autopilot/src/app/viewports/ac-help/viewport.vue
- packages/autopilot/src/app/viewports/api/viewport.vue
- packages/autopilot/src/app/viewports/extensions/ext-item.vue
- packages/autopilot/src/app/viewports/extensions/extensions.vue
- packages/autopilot/src/app/viewports/extensions/viewport.vue
- packages/autopilot/src/app/views/account-menu.vue
- packages/autopilot/src/app/views/first-run.vue
- packages/autopilot/src/app/views/topbar.vue
This PR does two things:
- refactors the `signup-warning` component to make it more standalone and less configurable (basically to establish proper separation of concerns with its clients);
- adds `bind` option which I'd like to propose as a more declarative substitution to mapping controllers inside `computed` which tends to be too repetitive for no apparent reason.
With regards to jittery behaviour: I wasn't able to resolve it, because `apiLogin` turns out to be quite complicated. Generally speaking, we should pay more attention to data flows;I'm guessing this is the problem which lead to people relying on "time machine" debugging style — but the more important point is: it doesn't necessarily have to be this complicated. I'm pretty confident that with few bits of refactoring the whole …
> chore: refactor signup-warning, introduce bind vue options

- .vscode/settings.json
- packages/autopilot/package-lock.json
- packages/autopilot/package.json
- packages/autopilot/src/app/components/signin-warning.vue
- packages/autopilot/src/app/controllers/api-login.ts
- packages/autopilot/src/app/controllers/extension-registry.ts
- packages/autopilot/src/app/controllers/roxi.ts
- packages/autopilot/src/app/entrypoint.ts
- packages/autopilot/src/app/viewports/ac-help/viewport.vue
- packages/autopilot/src/app/viewports/api/viewport.vue
- packages/autopilot/src/app/viewports/extensions/viewport.vue
- packages/autopilot/src/app/views/account-menu.vue
- packages/autopilot/src/app/views/proxy-select.vue
- packages/autopilot/src/app/views/topbar.vue
- packages/engine/src/main/extension.ts
Prerequisite of https://ubio-automation.atlassian.net/jira/software/projects/SM/boards/4?selectedIssue=ROBO-311
I've started working on "slow start" which ultimately converges at ApiLoginController making a lot of retries, and a bunch of auth-dependent services retrying on top of it. I started from refactoring to make things a bit cleaner.
Here's a summary.
1. Most controllers that use `UserData` (i.e. persist some state on filesystem) do this via an implicit pattern: state is read inside `init` and is written with `update`. There is currently no enforcement on this pattern (mostly because this would require mixins with generics which are not natively supported), but it's a good idea to stick with it, because at any time you can make reason about how your controller's state is represented …
> chore: refator ApiLoginController

- packages/autopilot/src/app/command.ts
- packages/autopilot/src/app/ui/modal-menu.ts
Fixes https://ubio-automation.atlassian.net/browse/ROBO-328
- affected for contexts, pipes and actions.
- When adding a new item, it focused on the previous item, as `modal-menu.hide()` triggers `focus()` before the new item is added.
> fix: focus on created item, not previous item

- packages/autopilot/src/app/controllers/api-login.ts
- packages/autopilot/src/app/overrides/api-request.ts
- packages/engine/package-lock.json
- packages/engine/package.json
ticket: https://ubio-automation.atlassian.net/browse/ROBO-342
When failed to renew accessToken with refreshToken, we should consider it as `singed out` and it should be notified to `apiLoginController` so that it can update its state/UI.
This PR is to emit `apiAuthInvalidated` events from apiRequest service when 401 response is returned.
> fix: invalidate refresh token when 401 received

- packages/worker/src/main/services/api.ts
- packages/worker/src/main/services/roxi.ts
- packages/worker/src/main/services/runner.ts
- packages/worker/src/main/services/state.ts
- packages/worker/src/main/types.ts
- packages/worker/src/test/helpers.ts
- packages/worker/src/test/server/api.ts
- packages/worker/src/test/specs/proxy.test.ts
Use a new endpoint that returns session applied connection
ticket: https://ubio-automation.atlassian.net/browse/ROBO-308
> feat: use `Proxy/getConnection` to get session for dynamic proxy

- packages/cdp/src/main/frame.ts
- packages/engine/src/test/specs/pipes/DOM.iframe.test.ts
I've looked briefly at the flaky dom/iframe test, and from the looks of it the recurring error appears to be genuine, i.e. it should indeed fail — but it's not easy to make it fail reliably to reproduce.
Explanation:
- the test navigates to the page with iframes hierarchy; standard `navigate` waits for `ready` event — which does **not** guarantee that all the frames load
- after that we immediately call `runtime.runPipeline`; unlike actions which invoke pipelines with retry, this one does not retry — so it fails immediately if the document isn't ready (which _should_ be the case if our execution environment is faster than Chrome's)
So I'm convinced it's the test that needs to be fixed, and not the code.
> fix: flaky DOM.iframe test

- packages/engine/src/main/services/proxy.ts
- packages/worker/src/main/services/proxy-setup.ts
- packages/worker/src/main/services/state.ts
- packages/worker/src/test/specs/proxy.test.ts
This simplifies the part where we obtain the default upstream, and also makes it possible for the code to remove `roxi` routing by label.
Should be a non-breaking change, but if it is, then staging CSI will scream.
> chore: refactor routing proxy bootstrapping

- packages/autopilot/src/app/modals/create-pipe-recipe.vue
- packages/autopilot/src/app/modals/edit-action-notes.vue
- packages/autopilot/src/app/modals/edit-bundle.vue
- packages/autopilot/src/app/modals/edit-pipe-notes.vue
- packages/autopilot/src/app/modals/open-automation.vue
- packages/autopilot/src/app/modals/save-automation.vue
- packages/autopilot/stylesheets/_inbox.css
- packages/autopilot/stylesheets/components/modal.css
- packages/autopilot/stylesheets/variables.css
I realise these changes just barely scratch the surface of what needs to be done, but it should provide a general direction.
More specifically, we should aim at:
- keeping components self-sufficient (i.e. `.automation-cloud > ` family of styles needs to be fixed with introducing more semantics)
- eventually removing `@ubio/css`, replacing it with just shared variables (because it's not maintained and it's hard to keep the changes in sync with it)
- if new common styles are introduced, they should follow general guidelines
- ad hoc styles are still possible, but should be minimised; `style="margin-left: var(--gap)"` is still viable — as long as it's just a single tweak (e.g. if we add more OR combine them with other scoped classes, then we don't use inline styles)
> chore: cleanup temporary css

- packages/autopilot/src/app/modals/open-automation.vue
- packages/autopilot/src/app/modals/save-automation.vue
- keep `select` and `input` elements inlined when the width is narrow
- format time for scripts in Open modal
> fix: ui bugs on save/open

- packages/autopilot/src/app/controllers/bundles.ts
- packages/autopilot/src/app/controllers/project.ts
- packages/autopilot/src/app/controllers/saveload.ts
- packages/engine/package-lock.json
- packages/engine/package.json
This brings back `stage: ''` which unblocks QA for the time being. The whole thing is booby-trapped with TODOs, so we don't forget to revisit this.
Note: I tried to consolidate the workarounds in one place, hence cleaned up some stuff. I also applied the modifications directly to `metadata` (b/c I figured even if the save fails, we'll end up over-writing them on next save anyway). But lmk if I wasn't supposed to be doing that for any other reason 🙏
> chore: return input stage back for QA tool

- packages/autopilot/src/app/components/service-select.vue
- packages/autopilot/src/app/controllers/api.ts
- packages/autopilot/src/app/controllers/app-menu.ts
- packages/autopilot/src/app/controllers/saveload.ts
- packages/autopilot/src/app/controllers/tools.ts
- packages/autopilot/src/app/modals/open-automation.vue
- packages/autopilot/src/app/modals/save-automation.vue
- packages/autopilot/src/app/viewports/script-editor/edit-default.vue
- packages/autopilot/stylesheets/_inbox.css
Spec can be found here: https://ubio-automation.atlassian.net/browse/ROBO-399
it includes:
- input+select for services list
- File > load as diff: show diff between current automation + loading automation
- File > Manage automation version: open dashboard's script version page
- Added `.select` style so we don't need to use `.input` class for select, also align with the spec
todo:
> feat: add searchable select component

- packages/autopilot/src/app/controllers/api-login.ts
ticket: https://ubio-automation.atlassian.net/browse/ROBO-386
Issue accessToken(if available) in `init()` of apiLogin controller so we can avoid token invalidation race condition when requests are concurrently triggered
> fix: get accessToken when initiating apiLogin

- packages/autopilot/src/app/controllers/project.ts
- packages/autopilot/src/app/controllers/saveload.ts
- packages/autopilot/src/app/controllers/tools.ts
- packages/autopilot/src/app/modals/open-automation.vue
- packages/autopilot/src/app/modals/save-automation.vue
ticket: https://ubio-automation.atlassian.net/browse/ROBO-427
diff base should not affect project's state, especially `project.automation.script` but the wrong event listener was set for `diffBaseSet` event and it unexpectedly updates the project's state that sometimes it saves an empty state after some of the actions mentioned in the ticket is performed.
This is also loosely related to how the `loadAsDiff` action is misunderstood, so I've renamed the `setAsDiff` property to loadAsDiff so it is more explicit, and update the project's state only when it's specified to `false` so thus we know setDiffBase is not related to updating project's state but separated operation.
> fix: remove setDiffBase event listener and loadDiffBase

- packages/autopilot/src/app/controllers/api-login.ts
Related to https://ubio-automation.atlassian.net/browse/ROBO-386
As a Desktop application, it is fair to issue `offline_access` token so that it doesn't get affected by SSO sessions.
The token will be valid for 30 days as default, but it will be extended if a user uses the offline token for a refresh token action at least once per 30 days(we can change it to expire regardless of the refresh if we prefer). more details:  https://www.keycloak.org/docs/latest/server_admin/#_offline-access
> feat: issue offline_access token for autopilot users

- packages/autopilot/src/app/controllers/api-login.ts
- packages/autopilot/src/app/controllers/roxi.ts
- packages/autopilot/src/app/overrides/api-request.ts
- packages/autopilot/src/app/views/account-menu.vue
- packages/engine/package-lock.json
- packages/engine/package.json
- packages/engine/src/main/services/api-request.ts
https://ubio-automation.atlassian.net/browse/ROBO-456
As request library should not invalidate refreshToken and delegate the responsibility to a client, Autopilot is actively checking the refreshToken invalidation for `authAgent` and also listen to its accessToken's change so that it can actively update it's state(account information etc).
- removed `isAuthenticated` method from `engine/api-request` as it is used by autopilot only.
- renamed `apiAuthInvalidated` to `apiAuthError` as auth will be invalidated when this event event is emitted
- it is possible to fetch the account details even after `init` phase as it subscribes to accessToken changes.
There is still issue that there's no ability to automatically obtain the accessToken when the machine was offline and then back online. The …
> fix: listen on accessToken change and fetch account when available

- packages/autopilot/src/app/controllers/composer.ts
- packages/autopilot/src/app/controllers/inspect.ts
- packages/autopilot/src/app/viewports/settings/preferences.vue
- packages/autopilot/src/app/views/inspect.vue
- packages/autopilot/src/app/views/root.vue
- packages/autopilot/stylesheets/article.css
This adds a preference to disable action composition.
One step further is to turn it off via inspect overlay — but I haven't yet figured a way to de-couple action composition and inspector (which is lower-level functionality).
Please lmk what you think @kyungeunni
> feat: make action composition disablable

- packages/autopilot/src/app/controllers/credentials.ts
- packages/engine/src/main/connector-action.ts
- packages/engine/src/main/services/credentials.ts
Part of connectors.
I noticed that `Result`outcome is empty object when assigning the whole response, so that we needed to build an object out of response and return them.
> fix: build response to object so that it can be used from get outcome

- packages/autopilot/src/app/controllers/api.ts
- packages/autopilot/src/app/controllers/extension-dev.ts
- packages/autopilot/src/app/controllers/extension-registry.ts
- packages/autopilot/src/app/controllers/helpdesk.ts
- packages/autopilot/src/app/modals/request-connector.vue
- packages/autopilot/src/app/viewports/extensions/ext-item.vue
- packages/autopilot/src/app/viewports/extensions/extensions.vue
- packages/autopilot/src/app/viewports/extensions/header.vue
- packages/autopilot/src/app/viewports/extensions/request-connector.vue
- packages/autopilot/src/app/viewports/extensions/viewport.vue
- packages/autopilot/src/app/views/notifications.vue
- packages/engine/src/main/extension.ts
ticket: https://ubio-automation.atlassian.net/browse/ROBO-463
> feat: address overall spec for extension viewport

- packages/autopilot/src/app/modals/create-credentials.vue
- packages/engine/src/main/connector.ts
- chore: change nav buttons to select in create-crdt, but show as plane text when only one option available 
Also changed the `create-credential` modal to be normal modal width instead of narrow as it break when there is a long lengthy of url, and it looks a bit packed when there are too many texts.
- fix: connectors: add ability to pass headers and body
It's due to some body object can't be part of parameters(e.g. nested properties etc)
> chore: improve create-credentials UI, update connector

- packages/autopilot/src/app/controllers/credentials.ts
- packages/autopilot/src/app/modals/create-credentials.vue
- packages/engine/src/main/connector.ts
Allow users to set their own scopes, it is needed as a few providers's the default scope specified in spec won't work universally for all the methods.
> feat: configurable oauth2 scope when creating crendentials

- packages/engine/src/main/connector.ts
Some complicated body parameters can not be described as parameters(e.g. nested object)
So having `body`  property in endpoint seems like an option to overcome this limitation.
> feat: add body which cannot be a part of parameters

- package-lock.json
- packages/autopilot/src/app/controllers/script-editor.ts
- packages/autopilot/src/app/viewports/script-editor/pipes/pipeline.vue
- packages/autopilot/src/app/viewports/settings/preferences.vue
- packages/engine/src/main/ctx.ts
- packages/engine/src/main/pipeline.ts
This fixes a lingering bug: workers are not supposed to collect intermediary pipeline results.
As a bonus, I've added a *developer-only* preference to disable feedback altogether, so that we can investigate memory leaks better.
> fix: do not collect pipeline feedback in workers

- packages/autopilot/src/app/viewports/script-flow/script-search.vue
ticket: https://ubio-automation.atlassian.net/browse/ROBO-529
script search queries don't stick together by adding margins around each tags
> fix: script search tag missing margins
